In [21]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [22]:
dataset_train = pd.read_csv('train.csv')
dataset_test = pd.read_csv('test.csv')
X= dataset_train.iloc[:, [True, False, True, False,True,True,True,True,False,True,True,True]]
y = dataset_train.iloc[:, 1].values

test_X= dataset_test.iloc[:, [True, True, False,True,True,True,True,False,True,True,True]]



In [23]:
X

PassengerId  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0              1       3    male  22.0      1      0   7.2500   NaN        S
1              2       1  female  38.0      1      0  71.2833   C85        C
2              3       3  female  26.0      0      0   7.9250   NaN        S
3              4       1  female  35.0      1      0  53.1000  C123        S
4              5       3    male  35.0      0      0   8.0500   NaN        S
..           ...     ...     ...   ...    ...    ...      ...   ...      ...
886          887       2    male  27.0      0      0  13.0000   NaN        S
887          888       1  female  19.0      0      0  30.0000   B42        S
888          889       3  female   NaN      1      2  23.4500   NaN        S
889          890       1    male  26.0      0      0  30.0000  C148        C
890          891       3    male  32.0      0      0   7.7500   NaN        Q

[891 rows x 9 columns]

In [24]:
X=X.values
test_X=test_X.values

In [25]:
X

array([[1, 3, 'male', ..., 7.25, nan, 'S'],
       [2, 1, 'female', ..., 71.2833, 'C85', 'C'],
       [3, 3, 'female', ..., 7.925, nan, 'S'],
       ...,
       [889, 3, 'female', ..., 23.45, nan, 'S'],
       [890, 1, 'male', ..., 30.0, 'C148', 'C'],
       [891, 3, 'male', ..., 7.75, nan, 'Q']], dtype=object)

In [26]:
y

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,

In [27]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 3:7])
X[:, 3:7] = imputer.transform(X[:, 3:7])

In [28]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(test_X[:, 3:7])
test_X[:, 3:7] = imputer.transform(test_X[:, 3:7])

In [29]:
X=X[:, 1:7]
test_X=test_X[:, 1:7]

In [30]:
X

array([[3, 'male', 22.0, 1.0, 0.0, 7.25],
       [1, 'female', 38.0, 1.0, 0.0, 71.2833],
       [3, 'female', 26.0, 0.0, 0.0, 7.925],
       ...,
       [3, 'female', 29.69911764705882, 1.0, 2.0, 23.45],
       [1, 'male', 26.0, 0.0, 0.0, 30.0],
       [3, 'male', 32.0, 0.0, 0.0, 7.75]], dtype=object)

In [31]:
test_X

array([[3, 'male', 34.5, 0.0, 0.0, 7.8292],
       [3, 'female', 47.0, 1.0, 0.0, 7.0],
       [2, 'male', 62.0, 0.0, 0.0, 9.6875],
       ...,
       [3, 'male', 38.5, 0.0, 0.0, 7.25],
       [3, 'male', 30.272590361445783, 0.0, 0.0, 8.05],
       [3, 'male', 30.272590361445783, 1.0, 1.0, 22.3583]], dtype=object)

In [32]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')

X = np.array(ct.fit_transform(X))
test_X=np.array(ct.fit_transform(test_X))

In [33]:
X

array([[0.0, 1.0, 3, ..., 1.0, 0.0, 7.25],
       [1.0, 0.0, 1, ..., 1.0, 0.0, 71.2833],
       [1.0, 0.0, 3, ..., 0.0, 0.0, 7.925],
       ...,
       [1.0, 0.0, 3, ..., 1.0, 2.0, 23.45],
       [0.0, 1.0, 1, ..., 0.0, 0.0, 30.0],
       [0.0, 1.0, 3, ..., 0.0, 0.0, 7.75]], dtype=object)

In [34]:
test_X

array([[0.0, 1.0, 3, ..., 0.0, 0.0, 7.8292],
       [1.0, 0.0, 3, ..., 1.0, 0.0, 7.0],
       [0.0, 1.0, 2, ..., 0.0, 0.0, 9.6875],
       ...,
       [0.0, 1.0, 3, ..., 0.0, 0.0, 7.25],
       [0.0, 1.0, 3, ..., 0.0, 0.0, 8.05],
       [0.0, 1.0, 3, ..., 1.0, 1.0, 22.3583]], dtype=object)

In [35]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)
test_X = sc.transform(test_X)

In [36]:
#from sklearn.linear_model import LogisticRegression
#classifier = LogisticRegression(random_state = 0)
#classifier.fit(X, y)

#from sklearn.neighbors import KNeighborsClassifier
#classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
#classifier.fit(X, y)

from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X, y)

#from sklearn.svm import SVC
#classifier = SVC(kernel = 'rbf', random_state = 0)
#classifier.fit(X, y)

#from sklearn.tree import DecisionTreeClassifier
#classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
#classifier.fit(X, y)

#from sklearn.ensemble import RandomForestClassifier
#classifier = RandomForestClassifier(n_estimators = 1000, criterion = 'entropy', random_state = 0)
#classifier.fit(X, y)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [37]:
y_test_data_frame = pd.read_csv('gender_submission.csv')
y_test = y_test_data_frame.iloc[:, 1].values

In [38]:
y_pred = classifier.predict(test_X)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))


[[0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]

In [39]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[266   0]
 [  0 152]]


1.0